vpc_cidr             = "10.0.0.0/16"
enable_dns_support   = true
enable_dns_hostnames = true
vpc_name             = "dev-vpc"
environment          = "dev"
public_subnet_cidr   = "10.0.0.1/24"
availability_zone    = "eu-central-1a"
private_subnet_cidr  = "10.0.2.0/24"
private_subnet_azs   = ["eu-central-1a", "eu-central-1b"]
public_subnet_azs    = ["us-west-2a", "us-west-2b"]
